### PR TITLE
add hash for chat-server

### PR DESCRIPTION
**Pull request by syamgk**

### CODE REVIEW

**Comment by vpavlin** [comment]
[test]

**Comment by vpavlin** [comment]
Looks good https://ci.centos.org/view/Devtools/job/devtools-saas-chat-promote-to-prod-test/1/console

**Comment by aditya-konarde** [comment]
Do remember to 'rebase and merge' when we want to- since #10 has been merged after this.

**Comment by vpavlin** [comment]
[test]

**Pull request merged**
